services:
    db:
        image: postgres:17-alpine
        volumes:
            - joplindb:/var/lib/postgresql/data
        container_name: Joplin-db
        ports:
            - 5432:5432
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=joplin
    app:
        image: joplin/server:latest
        container_name: Joplin
        depends_on:
            - db
        ports:
            - 22300:22300
        restart: always
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=http://IP OF YOUR SERVER:22300
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            
volumes:
  joplindb: