services:
  docmost:
    image: docmost/docmost:latest
    container_name: Docmost
    depends_on:
      - db
      - redis
    environment:
      APP_SECRET: #REPLACE_WITH_LONG_SECRET
      DATABASE_URL: "postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - 41946:3000
    restart: always
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:17-alpine
    container_name: Docmost-db
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest-alpine
    container_name: Docmost-redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data: