volumes:
  uptime-kuma:

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: Uptime-Kuma
    volumes:
      - uptime-kuma:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: always