volumes:
  hbbs:
  hbbr:

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - hbbs:/root
    network_mode: "host"

    depends_on:
      - hbbr
    restart: always

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - hbbr:/root
    network_mode: "host"
    restart: always
