services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

volumes:
  n8n_data: