services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: Navidrome
    ports:
      - 21480:4533
    restart: always
    environment:
      ND_DEVACTIVITYPANEL: false
      ND_DEVFASTACCESSCOVERART: true
    volumes:
      - data:/data
      - music:/music
      
volumes:
  data:
  music: