volumes:
  traggo:

services:
  traggo:
    image: traggo/server:latest
    ports:
      - 46700:3030
    environment:
      TRAGGO_DEFAULT_USER_NAME: "admin"
      TRAGGO_DEFAULT_USER_PASS: "admin"
    volumes:
      - traggo:/opt/traggo/data